# Configuration file for ${project.name} v${project.version}

# localized language support
language: en-US

# enabled worlds list
# if this list is empty, all worlds will be added to the enabled worlds list
# otherwise, only listed worlds will be added to the enabled worlds list
# Note: explicitly set if empty list for testing
enabled-worlds: []
#  - enabled_world1
#  - enabled_world2

# disabled worlds list
# these worlds will be removed from the enabled worlds list created by the previous setting
# Note: explicitly set if empty list for testing
disabled-worlds: []
#  - disabled_world1
#  - disabled_world2

# default enabled setting for new graveyards
default-enabled: true

# default hidden setting for new graveyards
default-hidden: true

# default player respawn safety time (in seconds)
safety-time: 15

# default distance from graveyard for discovery
discovery-range: 50

# interval to check for discovery (in ticks)
discovery-interval: 40

# number of Graveyards shown per page in list command
list-page-size: 5

# respawn listener priority ( LOWEST | LOW | NORMAL | HIGH | HIGHEST )
# NOTE: priority LOWEST happens before all others, HIGHEST happens after all others
# this should only be changed if you are experiencing a conflict with another plugin
respawn-priority: NORMAL

# display titles for discovery and respawn rather than chat message
titles-enabled: true

# play sound effects
sound-effects: true
